# Generated by Django 5.0.6 on 2024-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='programming_status',
            field=models.CharField(choices=[('Full Stack', 'Full Stack'), ('Backend Development', 'Backend Development'), ('UX-UI Development', 'UX-UI Development'), ('Frontend Development', 'Frontend Development')], max_length=100, null=True),
        ),
    ]
