# Generated by Django 5.0.6 on 2024-06-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_employees_programming_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'сотрудника', 'verbose_name_plural': 'сотрудники'},
        ),
    ]
