# Generated by Django 5.0.6 on 2024-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_tag_rewiews_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Загрузите фото'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rezume',
            field=models.FileField(blank=True, null=True, upload_to='rezume/', verbose_name='Загрузите резюме'),
        ),
    ]
