# Generated by Django 5.0.6 on 2024-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_employees_image_alter_employees_rezume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='programming_status',
            field=models.CharField(choices=[('action movie', 'action movie'), ('romance', 'romance'), ('Fantastic', 'Fantastic'), ('Mystic', 'Mystic')], max_length=100, null=True),
        ),
    ]
